### ISSUE TITLE
Power of Three Not Working (Unimplemented).

### ISSUE THREAD

**Issue by minhd-vu** [SirGoldenNugget/Computer-Science#1]
Everything else but the power of three method has been implemented.

**Comment by poopmuncher2015** [comment]
if(num % 3 == 0)
{
if(num == 3)
{
return powerOfThree(num / 3);
}
}
else
{
return false;
}

**Comment by poopmuncher2015** [comment]
if(num <= 5)
         {
            if(num == 3)
            {
               return true;
            }
            else
            {
               return false;
            }
         }
         else if(num % 3 == 0)
         {
            return powerOfThree(num / 3);
         }
         else
         {
            return false;
         }

**Comment by Penguin** [comment]
public static boolean powerOfThree (int num)
   {
      if(num <= 0 || num % 3 > 0)
      {
    	  return false;
      }
      else if(num > 1)
      {
    	  powerOfThree(num/3);
    	  return true;
      }
      else
    	  return true;
   }
